//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostavkiTovarovApp.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ContractID { get; set; }
        public int TovarID { get; set; }
        public int Amount { get; set; }
        public decimal Profit { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
